package infra_connector

const (
	K8sCluster       = "k8s-cluster"
	DataPlaneAddSvc  = "dataplane-add-svc"
	Resource         = "resource"
	CloudAccount     = "account"
	Types            = "types"
	CloudProviders   = "cloud-providers"
	TshirtSize       = "t-shirt-size"
	Certificate      = "certificate"
	Internal         = "internal"
	ObjectStore      = "objectstore"
	DNSConfig        = "dnsconfig"
	FleetMangement   = "fleet-management"
	OrgHealth        = "org-health"
	Details          = "details"
	Dataplane        = "dataplane"
	Count            = "count"
	Clusters         = "clusters"
	DataplaneOnboard = "dataplane-onboard"
	Sync             = "sync"
	Eligible         = "eligible"
	HelmRelase       = "dataplane-helm-release"
	Release          = "release"
	AccountMetadata  = "account-metadata"
	StorageClass     = "storage-class"
)
